//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fichier
    {
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
        public string IconeUrl { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<double> Taille { get; set; }
        public string Auteur { get; set; }
    }
}
